name: Surge PR
on:
  pull_request:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to fearless-development-test.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'fearless-development-test.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
      - run: echo "🚀 Test deployment finished."
